#!/usr/bin/env python3
"""Generate slide-ready figures directly from raw benchmark CSV files.

This replaces symlink/crop behavior and ensures every plot is generated by
Python specifically for the Beamer deck.
"""

from __future__ import annotations

import argparse
from pathlib import Path

try:
    import matplotlib.pyplot as plt
    import numpy as np
    import pandas as pd
except ImportError as exc:
    raise SystemExit(
        "Missing plotting dependencies. Install: pandas matplotlib numpy"
    ) from exc


ALGO_ORDER = [
    "Naive",
    "Rabin-Karp",
    "Vectorized RK",
    "Greedy KMP",
    "Greedy BM",
    "Bird-KMP",
    "Bird-BM",
]

ALGO_COLORS = {
    "Naive": "#e74c3c",
    "Rabin-Karp": "#3498db",
    "Vectorized RK": "#2ecc71",
    "Greedy KMP": "#9b59b6",
    "Greedy BM": "#f39c12",
    "Bird-KMP": "#1abc9c",
    "Bird-BM": "#e67e22",
}


def configure_style() -> None:
    plt.rcParams.update(
        {
            "font.size": 10,
            "axes.titlesize": 11,
            "axes.labelsize": 10,
            "legend.fontsize": 8,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "axes.grid": True,
            "grid.alpha": 0.30,
            "grid.linestyle": "--",
            "grid.linewidth": 0.6,
        }
    )


def algo_list_from_frame(df: pd.DataFrame) -> list[str]:
    present = set(df["algorithm"].dropna().unique())
    ordered = [a for a in ALGO_ORDER if a in present]
    extras = sorted(a for a in present if a not in ALGO_ORDER)
    return ordered + extras


def color_for(algo: str) -> str:
    return ALGO_COLORS.get(algo, "#4E5D6C")


def read_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Missing CSV: {path}")
    return pd.read_csv(path)


def save_figure(fig: plt.Figure, *paths: Path) -> None:
    fig.tight_layout()
    for path in paths:
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_symlink() or path.exists():
            path.unlink()
        fig.savefig(path, dpi=220, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def cleanup_legacy_files(out_dir: Path) -> None:
    for pattern in ("*_crop_left.png", "*_crop_right.png"):
        for path in out_dir.glob(pattern):
            path.unlink()


def make_subplot_grid(count: int, max_cols: int = 2, panel_w: float = 5.8, panel_h: float = 3.2) -> tuple[plt.Figure, np.ndarray]:
    ncols = max(1, min(max_cols, count))
    nrows = int(np.ceil(count / ncols))
    fig, axes = plt.subplots(nrows, ncols, figsize=(panel_w * ncols, panel_h * nrows), sharey=False)
    if isinstance(axes, np.ndarray):
        flat_axes = axes.reshape(-1)
    else:
        flat_axes = np.array([axes])
    return fig, flat_axes


def plot_random_comparisons_vs_textsize(df_random: pd.DataFrame, out_dir: Path) -> None:
    agg = (
        df_random.groupby(["algorithm", "pattern_size", "text_size"])["comparisons"]
        .mean()
        .reset_index()
    )
    pats = sorted(agg["pattern_size"].unique())
    algos = algo_list_from_frame(agg)

    fig, axes = make_subplot_grid(len(pats), max_cols=2, panel_w=5.6, panel_h=3.2)

    for idx, (ax, pat) in enumerate(zip(axes, pats)):
        sub = agg[agg["pattern_size"] == pat]
        for algo in algos:
            d = sub[sub["algorithm"] == algo].sort_values("text_size")
            if d.empty:
                continue
            ax.plot(
                d["text_size"],
                d["comparisons"],
                marker="o",
                linewidth=1.8,
                markersize=3.5,
                label=algo,
                color=color_for(algo),
            )
        ax.set_title(f"Pattern {int(pat)}x{int(pat)}")
        ax.set_xlabel("Text Size (NxN)")
        ax.set_ylabel("Avg. Comparisons")
        if idx == 0:
            ax.legend(loc="upper left", fontsize=6.8, frameon=False)

    for ax in axes[len(pats):]:
        ax.set_visible(False)

    fig.suptitle("Comparisons vs Text Size (Random, avg over seeds)", y=1.02, fontsize=12, fontweight="bold")

    save_figure(
        fig,
        out_dir / "random_comparisons_vs_textsize.png",
        out_dir / "random_comparisons_vs_textsize_focus.png",
    )


def plot_random_comparisons_vs_patsize(df_random: pd.DataFrame, out_dir: Path) -> None:
    agg = (
        df_random.groupby(["algorithm", "pattern_size", "text_size"])["comparisons"]
        .mean()
        .reset_index()
    )
    text_sizes = [50, 100, 200, 500]
    available = set(agg["text_size"].unique().tolist())
    text_sizes = [t for t in text_sizes if t in available]
    if not text_sizes:
        text_sizes = sorted(agg["text_size"].unique())[:4]
    algos = algo_list_from_frame(agg)

    fig, axes = make_subplot_grid(len(text_sizes), max_cols=2, panel_w=5.6, panel_h=3.2)

    for idx, (ax, text_size) in enumerate(zip(axes, text_sizes)):
        sub = agg[agg["text_size"] == text_size]
        for algo in algos:
            d = sub[sub["algorithm"] == algo].sort_values("pattern_size")
            if d.empty:
                continue
            ax.plot(
                d["pattern_size"],
                d["comparisons"],
                marker="s",
                linewidth=1.8,
                markersize=3.5,
                label=algo,
                color=color_for(algo),
            )
        ax.set_title(f"Text {int(text_size)}x{int(text_size)}")
        ax.set_xlabel("Pattern Size (MxM)")
        ax.set_ylabel("Avg. Comparisons")
        if idx == 0:
            ax.legend(loc="upper left", fontsize=6.8, frameon=False)

    for ax in axes[len(text_sizes):]:
        ax.set_visible(False)

    fig.suptitle("Comparisons vs Pattern Size (Random, avg over seeds)", y=1.02, fontsize=12, fontweight="bold")

    save_figure(
        fig,
        out_dir / "random_comparisons_vs_patsize.png",
        out_dir / "random_comparisons_vs_patsize_focus.png",
    )


def plot_random_wallclock(df_random: pd.DataFrame, out_dir: Path) -> None:
    agg = (
        df_random.groupby(["algorithm", "pattern_size", "text_size"])["wall_sec"]
        .mean()
        .reset_index()
    )
    pats = sorted(agg["pattern_size"].unique())
    algos = algo_list_from_frame(agg)

    fig, axes = make_subplot_grid(len(pats), max_cols=2, panel_w=5.6, panel_h=3.2)

    for idx, (ax, pat) in enumerate(zip(axes, pats)):
        sub = agg[agg["pattern_size"] == pat]
        for algo in algos:
            d = sub[sub["algorithm"] == algo].sort_values("text_size")
            if d.empty:
                continue
            ax.plot(
                d["text_size"],
                d["wall_sec"],
                marker="o",
                linewidth=1.8,
                markersize=3.5,
                label=algo,
                color=color_for(algo),
            )
        ax.set_title(f"Pattern {int(pat)}x{int(pat)}")
        ax.set_xlabel("Text Size (NxN)")
        ax.set_ylabel("Avg. Wall-Clock (s)")
        if idx == 0:
            ax.legend(loc="upper left", fontsize=6.8, frameon=False)

    for ax in axes[len(pats):]:
        ax.set_visible(False)

    fig.suptitle("Wall-Clock vs Text Size (Random, avg over seeds)", y=1.02, fontsize=12, fontweight="bold")

    save_figure(
        fig,
        out_dir / "random_wallclock.png",
        out_dir / "random_wallclock_focus.png",
    )


def _ordered_algos_for_bars(df: pd.DataFrame) -> pd.DataFrame:
    order_map = {a: i for i, a in enumerate(ALGO_ORDER)}
    return df.assign(_order=df["algorithm"].map(lambda x: order_map.get(x, 10_000))).sort_values("_order")


def plot_qr_avg_comparisons(df_qr: pd.DataFrame, out_dir: Path) -> None:
    agg = (
        df_qr.groupby("algorithm", as_index=False)["comparisons"]
        .mean()
        .pipe(_ordered_algos_for_bars)
    )
    fig, ax = plt.subplots(figsize=(10.6, 4.2))
    bars = ax.bar(
        agg["algorithm"],
        agg["comparisons"],
        color=[color_for(a) for a in agg["algorithm"]],
        edgecolor="black",
        linewidth=0.5,
    )
    ax.set_title("Average Comparisons on QR Inputs", fontweight="bold")
    ax.set_xlabel("Algorithm")
    ax.set_ylabel("Avg. Comparisons")
    ax.tick_params(axis="x", rotation=20)
    ax.bar_label(bars, fmt="%.0f", padding=3, fontsize=8)
    save_figure(fig, out_dir / "qr_avg_comparisons.png")


def plot_qr_per_image(df_qr: pd.DataFrame, out_dir: Path) -> None:
    algos = algo_list_from_frame(df_qr)
    fig, ax = plt.subplots(figsize=(10.8, 4.6))
    for algo in algos:
        sub = df_qr[df_qr["algorithm"] == algo].sort_values("qr_idx")
        if sub.empty:
            continue
        ax.plot(
            sub["qr_idx"],
            sub["comparisons"],
            linewidth=1.4,
            marker=".",
            markersize=3.0,
            label=algo,
            color=color_for(algo),
        )
    ax.set_title("Comparisons per QR Image", fontweight="bold")
    ax.set_xlabel("QR Index")
    ax.set_ylabel("Comparisons")
    ax.legend(ncol=4, loc="upper center", bbox_to_anchor=(0.5, -0.16), frameon=False)
    save_figure(
        fig,
        out_dir / "qr_per_image_comparisons.png",
        out_dir / "qr_per_image_comparisons_focus.png",
    )


def plot_qr_wallclock(df_qr: pd.DataFrame, out_dir: Path) -> None:
    agg = (
        df_qr.groupby("algorithm", as_index=False)["wall_sec"]
        .mean()
        .pipe(_ordered_algos_for_bars)
    )
    fig, ax = plt.subplots(figsize=(10.6, 4.2))
    bars = ax.bar(
        agg["algorithm"],
        agg["wall_sec"],
        color=[color_for(a) for a in agg["algorithm"]],
        edgecolor="black",
        linewidth=0.5,
    )
    ax.set_title("Average Wall-Clock on QR Inputs", fontweight="bold")
    ax.set_xlabel("Algorithm")
    ax.set_ylabel("Avg. Wall-Clock (s)")
    ax.tick_params(axis="x", rotation=20)
    ax.bar_label(bars, fmt="%.4f", padding=3, fontsize=8)
    save_figure(fig, out_dir / "qr_wallclock.png")


def plot_contrived_comparisons(df_contrived: pd.DataFrame, out_dir: Path) -> None:
    algos = algo_list_from_frame(df_contrived)
    fig, ax = plt.subplots(figsize=(10.6, 4.2))
    for algo in algos:
        sub = df_contrived[df_contrived["algorithm"] == algo].sort_values("text_size")
        if sub.empty:
            continue
        ax.plot(
            sub["text_size"],
            sub["comparisons"],
            marker="o",
            markersize=3.4,
            linewidth=1.8,
            label=algo,
            color=color_for(algo),
        )
    ax.set_title("Comparisons vs Text Size (Contrived)", fontweight="bold")
    ax.set_xlabel("Text Size (NxN)")
    ax.set_ylabel("Comparisons")
    ax.legend(ncol=4, loc="upper center", bbox_to_anchor=(0.5, -0.18), frameon=False)
    save_figure(fig, out_dir / "contrived_comparisons_vs_textsize.png")


def plot_contrived_wallclock(df_contrived: pd.DataFrame, out_dir: Path) -> None:
    algos = algo_list_from_frame(df_contrived)
    fig, ax = plt.subplots(figsize=(10.6, 4.2))
    for algo in algos:
        sub = df_contrived[df_contrived["algorithm"] == algo].sort_values("text_size")
        if sub.empty:
            continue
        ax.plot(
            sub["text_size"],
            sub["wall_sec"],
            marker="s",
            markersize=3.4,
            linewidth=1.8,
            label=algo,
            color=color_for(algo),
        )
    ax.set_title("Wall-Clock vs Text Size (Contrived)", fontweight="bold")
    ax.set_xlabel("Text Size (NxN)")
    ax.set_ylabel("Wall-Clock (s)")
    ax.legend(ncol=4, loc="upper center", bbox_to_anchor=(0.5, -0.18), frameon=False)
    save_figure(fig, out_dir / "contrived_wallclock.png")


def plot_summary_all_sections(df_random: pd.DataFrame, df_qr: pd.DataFrame, df_contrived: pd.DataFrame, out_dir: Path) -> None:
    random_avg = df_random.groupby("algorithm")["comparisons"].mean().rename("random_avg")
    qr_avg = df_qr.groupby("algorithm")["comparisons"].mean().rename("qr_avg")
    contrived_avg = df_contrived.groupby("algorithm")["comparisons"].mean().rename("contrived_avg")
    summary = pd.concat([random_avg, qr_avg, contrived_avg], axis=1)
    summary = summary.reindex(algo_list_from_frame(summary.reset_index().rename(columns={"index": "algorithm"})))

    x = np.arange(len(summary.index))
    width = 0.24
    fig, ax = plt.subplots(figsize=(11.8, 4.4))
    series = [
        ("random_avg", "Random", "#3498db"),
        ("qr_avg", "QR", "#e74c3c"),
        ("contrived_avg", "Contrived", "#2ecc71"),
    ]
    for i, (col, label, color) in enumerate(series):
        vals = summary[col].to_numpy()
        ax.bar(
            x + (i - 1) * width,
            vals,
            width=width,
            label=label,
            color=color,
            alpha=0.90,
            edgecolor="black",
            linewidth=0.45,
        )

    ax.set_title("Average Comparisons by Section and Algorithm", fontweight="bold")
    ax.set_ylabel("Avg. Comparisons")
    ax.set_xticks(x)
    ax.set_xticklabels(summary.index, rotation=20, ha="right")
    ax.legend(ncol=3)
    save_figure(fig, out_dir / "summary_all_sections.png")


def plot_head_to_head(df_head: pd.DataFrame, out_dir: Path) -> None:
    df = _ordered_algos_for_bars(df_head.copy())
    fig, axes = plt.subplots(1, 2, figsize=(11.8, 4.2))

    bars1 = axes[0].bar(
        df["algorithm"],
        df["comparisons"],
        color=[color_for(a) for a in df["algorithm"]],
        edgecolor="black",
        linewidth=0.5,
    )
    axes[0].set_title("Equality Comparisons", fontweight="bold")
    axes[0].set_ylabel("Comparisons")
    axes[0].tick_params(axis="x", rotation=20)
    axes[0].bar_label(bars1, fmt=lambda v: f"{int(v):,}", fontsize=7, padding=2)

    bars2 = axes[1].bar(
        df["algorithm"],
        df["wall_sec"],
        color=[color_for(a) for a in df["algorithm"]],
        edgecolor="black",
        linewidth=0.5,
    )
    axes[1].set_title("Wall-Clock (s)", fontweight="bold")
    axes[1].set_ylabel("Seconds")
    axes[1].tick_params(axis="x", rotation=20)
    axes[1].bar_label(bars2, fmt=lambda v: f"{v:.2f}s", fontsize=7, padding=2)

    fig.suptitle("Head-to-Head on Maximum Input", y=1.02, fontsize=12, fontweight="bold")
    save_figure(fig, out_dir / "head_to_head.png")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate beamer-friendly figures from CSVs")
    parser.add_argument("--source-dir", type=Path, default=Path("."))
    parser.add_argument("--out-dir", type=Path, default=Path("slides/figures"))
    args = parser.parse_args()

    configure_style()

    src_dir = args.source_dir.resolve()
    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    cleanup_legacy_files(out_dir)

    df_random = read_csv(src_dir / "results_random.csv")
    df_qr = read_csv(src_dir / "results_qr.csv")
    df_contrived = read_csv(src_dir / "results_contrived.csv")
    df_head = read_csv(src_dir / "results_head_to_head.csv")

    plot_random_comparisons_vs_textsize(df_random, out_dir)
    plot_random_comparisons_vs_patsize(df_random, out_dir)
    plot_random_wallclock(df_random, out_dir)
    plot_qr_avg_comparisons(df_qr, out_dir)
    plot_qr_per_image(df_qr, out_dir)
    plot_qr_wallclock(df_qr, out_dir)
    plot_contrived_comparisons(df_contrived, out_dir)
    plot_contrived_wallclock(df_contrived, out_dir)
    plot_summary_all_sections(df_random, df_qr, df_contrived, out_dir)
    plot_head_to_head(df_head, out_dir)

    print(f"Generated slide figures in: {out_dir}")


if __name__ == "__main__":
    main()
