#!/usr/bin/env python3
"""Recompute benchmark metrics from raw CSVs and emit CSV + LaTeX macros.

This script is intentionally dependency-free (standard library only).
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

SectionName = str
Algorithm = str


def read_rows(path: Path, numeric_fields: Iterable[str]) -> List[dict]:
    rows: List[dict] = []
    with path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            for field in numeric_fields:
                if field in row and row[field] not in ("", None):
                    row[field] = float(row[field])
            rows.append(row)
    return rows


def mean(values: Iterable[float]) -> float:
    vals = list(values)
    return sum(vals) / len(vals) if vals else float("nan")


def mean_by_algo(rows: List[dict], metric: str) -> Dict[Algorithm, float]:
    agg: Dict[Algorithm, List[float]] = defaultdict(list)
    for row in rows:
        agg[row["algorithm"]].append(float(row[metric]))
    return {algo: mean(vals) for algo, vals in agg.items()}


def rank_smallest(metric_by_algo: Dict[Algorithm, float]) -> List[Tuple[Algorithm, float]]:
    return sorted(metric_by_algo.items(), key=lambda kv: kv[1])


def sanitize(text: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]", "", text)
    if not cleaned:
        return "Unknown"
    if cleaned[0].isdigit():
        cleaned = f"N{cleaned}"
    return cleaned


def fmt_float(value: float, decimals: int = 3) -> str:
    return f"{value:.{decimals}f}"


def write_summary_csv(
    out_csv: Path,
    section_metrics: Dict[SectionName, Dict[str, Dict[Algorithm, float]]],
    head_rows: List[dict],
) -> None:
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with out_csv.open("w", newline="", encoding="utf-8") as f:
        fieldnames = ["section", "metric", "algorithm", "value", "rank"]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for section, metrics in section_metrics.items():
            for metric, algo_map in metrics.items():
                ranked = rank_smallest(algo_map)
                for rank, (algo, value) in enumerate(ranked, start=1):
                    writer.writerow(
                        {
                            "section": section,
                            "metric": metric,
                            "algorithm": algo,
                            "value": f"{value:.9f}",
                            "rank": rank,
                        }
                    )

        for row in sorted(head_rows, key=lambda r: float(r["wall_sec"])):
            writer.writerow(
                {
                    "section": "head_to_head",
                    "metric": "wall_sec",
                    "algorithm": row["algorithm"],
                    "value": row["wall_sec"],
                    "rank": "",
                }
            )
            writer.writerow(
                {
                    "section": "head_to_head",
                    "metric": "comparisons",
                    "algorithm": row["algorithm"],
                    "value": row["comparisons"],
                    "rank": "",
                }
            )


def macro_line(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def write_macros_tex(
    out_tex: Path,
    section_metrics: Dict[SectionName, Dict[str, Dict[Algorithm, float]]],
    random_rows: List[dict],
    qr_rows: List[dict],
    contrived_rows: List[dict],
    head_rows: List[dict],
) -> None:
    out_tex.parent.mkdir(parents=True, exist_ok=True)

    lines: List[str] = []
    lines.append("% Auto-generated by scripts/recompute_metrics.py")
    ts = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
    lines.append(macro_line("GeneratedTimestampUTC", ts.replace("+00:00", "Z")))

    lines.append(macro_line("RandomRowCount", str(len(random_rows))))
    lines.append(macro_line("QrRowCount", str(len(qr_rows))))
    lines.append(macro_line("ContrivedRowCount", str(len(contrived_rows))))
    lines.append(macro_line("HeadToHeadRowCount", str(len(head_rows))))

    qr_files = sorted({row.get("qr_file", "") for row in qr_rows if row.get("qr_file")})
    lines.append(macro_line("QrImageCount", str(len(qr_files))))

    section_prefix = {
        "random": "Random",
        "qr": "Qr",
        "contrived": "Contrived",
    }

    for section, prefix in section_prefix.items():
        comp_ranked = rank_smallest(section_metrics[section]["comparisons"])
        time_ranked = rank_smallest(section_metrics[section]["wall_sec"])

        lines.append(macro_line(f"{prefix}BestCompAlgo", comp_ranked[0][0]))
        lines.append(macro_line(f"{prefix}BestCompValue", fmt_float(comp_ranked[0][1], 1)))
        lines.append(macro_line(f"{prefix}BestTimeAlgo", time_ranked[0][0]))
        lines.append(macro_line(f"{prefix}BestTimeValue", fmt_float(time_ranked[0][1], 6)))

        for algo, value in comp_ranked:
            lines.append(macro_line(f"{prefix}Comp{sanitize(algo)}", fmt_float(value, 3)))
        for algo, value in time_ranked:
            lines.append(macro_line(f"{prefix}Time{sanitize(algo)}", fmt_float(value, 6)))

    head_time_sorted = sorted(head_rows, key=lambda r: float(r["wall_sec"]))
    head_comp_sorted = sorted(head_rows, key=lambda r: float(r["comparisons"]))
    naive_row = next((r for r in head_rows if r["algorithm"] == "Naive"), None)
    if naive_row is None:
        raise ValueError("Head-to-head CSV must include algorithm=Naive")

    naive_time = float(naive_row["wall_sec"])
    speedups: Dict[Algorithm, float] = {}
    for row in head_rows:
        algo = row["algorithm"]
        t = float(row["wall_sec"])
        if t > 0:
            speedups[algo] = naive_time / t

    best_speedup_algo, best_speedup_val = max(speedups.items(), key=lambda kv: kv[1])

    lines.append(macro_line("HeadBestTimeAlgo", head_time_sorted[0]["algorithm"]))
    lines.append(macro_line("HeadBestTimeValue", fmt_float(float(head_time_sorted[0]["wall_sec"]), 4)))
    lines.append(macro_line("HeadBestCompAlgo", head_comp_sorted[0]["algorithm"]))
    lines.append(macro_line("HeadBestCompValue", str(int(float(head_comp_sorted[0]["comparisons"])))))
    lines.append(macro_line("HeadNaiveTimeValue", fmt_float(naive_time, 4)))
    lines.append(macro_line("HeadBestSpeedupAlgo", best_speedup_algo))
    lines.append(macro_line("HeadBestSpeedupValue", fmt_float(best_speedup_val, 2)))

    for row in head_rows:
        algo = sanitize(row["algorithm"])
        lines.append(macro_line(f"HeadTime{algo}", fmt_float(float(row["wall_sec"]), 4)))
        lines.append(macro_line(f"HeadComp{algo}", str(int(float(row["comparisons"])))))
        lines.append(macro_line(f"HeadSpeedupVsNaive{algo}", fmt_float(speedups[row["algorithm"]], 2)))

    out_tex.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Recompute metrics for slide callouts")
    parser.add_argument("--random", required=True, type=Path)
    parser.add_argument("--qr", required=True, type=Path)
    parser.add_argument("--contrived", required=True, type=Path)
    parser.add_argument("--head2head", required=True, type=Path)
    parser.add_argument("--out-csv", required=True, type=Path)
    parser.add_argument("--out-tex", required=True, type=Path)
    args = parser.parse_args()

    random_rows = read_rows(args.random, ("comparisons", "wall_sec"))
    qr_rows = read_rows(args.qr, ("comparisons", "wall_sec"))
    contrived_rows = read_rows(args.contrived, ("comparisons", "wall_sec"))
    head_rows = read_rows(args.head2head, ("comparisons", "wall_sec"))

    section_metrics: Dict[SectionName, Dict[str, Dict[Algorithm, float]]] = {
        "random": {
            "comparisons": mean_by_algo(random_rows, "comparisons"),
            "wall_sec": mean_by_algo(random_rows, "wall_sec"),
        },
        "qr": {
            "comparisons": mean_by_algo(qr_rows, "comparisons"),
            "wall_sec": mean_by_algo(qr_rows, "wall_sec"),
        },
        "contrived": {
            "comparisons": mean_by_algo(contrived_rows, "comparisons"),
            "wall_sec": mean_by_algo(contrived_rows, "wall_sec"),
        },
    }

    write_summary_csv(args.out_csv, section_metrics, head_rows)
    write_macros_tex(args.out_tex, section_metrics, random_rows, qr_rows, contrived_rows, head_rows)


if __name__ == "__main__":
    main()
